CC = g++ 
CFLAGS = -std=c++11 -Wall -Werror

all: PhonePricePrediction.out

PhonePricePrediction.out: main.cpp
	$(CC) $(CFLAGS) main.cpp -o PhonePricePrediction.out


.PHONY: clean
clean:
	rm PhonePricePrediction.out